// AUTO-GENERATED by scripts/wiki-generate.mjs from wiki.config.yaml - do not hand-edit.
// Every value here is a literal copied from wiki.config.yaml - never LLM-generated.

export const wikiConfig = {
  "title": "OrderMate Docs",
  "description": "API reference, guides, and features for Clover POS order management.",
  "theme": {
    "accent": "#FF9F43",
    "accentHover": "#e68a2e",
    "accentMuted": "rgba(255, 159, 67, 0.1)"
  },
  "favicon": "/favicon.svg",
  "githubUrl": "https://github.com/11thandOrange/OrderMate",
  "proxyBaseUrl": "https://ordermate-wiki-backend.example.com",
  "targetApiBaseUrl": "https://api.clover.com"
} as const;
