// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar, which IS safe
// (and expected) to be hand-edited between generator runs - the merge
// logic in scripts/wiki-extractors/merge.mjs never overwrites or removes
// entries whose extracted source content has not changed.

import type { AutomationDoc } from '../types';
import data from './automation.generated.json';

export const automation = data as unknown as AutomationDoc[];

export function getAutomation(slug: string) {
  return automation.find((a) => a.slug === slug);
}
