// AUTO-GENERATED by scripts/wiki-generate.mjs from wiki.config.yaml's enabled extractors - do not hand-edit.

import type { NavSection } from '../types';
import { features } from './features';
import { endpointGroups } from './endpoints';
import { workflows } from './workflows';
import { automation } from './automation';
import { testSuites } from './tests';
import { markdownPages } from './pages';

// No "Home" entry: the site title in the header is the home link.
export const topNav: { title: string; href: string }[] = [
  { title: "Features", href: '/features' },
  { title: "API Reference", href: '/api' },
  { title: "CI/CD", href: '/ci-cd' },
  { title: "Automation", href: '/automation' },
  { title: "Test Coverage", href: '/tests' },
  { title: "Changelog", href: '/changelog' },
];

export const sidebarSections: Record<string, NavSection> = {
  'features': { title: "Features", href: '/features', children: features.map((f) => ({ title: f.title, href: `/features/${f.slug}` })) },
  'api': { title: "API Reference", href: '/api', children: endpointGroups.map((g) => ({ title: g.title, href: `/api/${g.slug}` })) },
  'ci-cd': { title: "CI/CD", href: '/ci-cd', children: workflows.map((w) => ({ title: w.title, href: `/ci-cd/${w.slug}` })) },
  'automation': { title: "Automation", href: '/automation', children: automation.map((a) => ({ title: a.name, href: `/automation/${a.slug}` })) },
  'tests': { title: "Test Coverage", href: '/tests', children: testSuites.map((t) => ({ title: t.name, href: `/tests/${t.slug}` })) },
  'changelog': { title: "Changelog", href: '/changelog', children: markdownPages.filter((p) => p.navSection === "Changelog").map((p) => ({ title: p.title, href: `/changelog/${p.slug}` })) },
};

export function sectionKeyForPath(pathname: string): string {
  const seg = pathname.split('/').filter(Boolean)[0] ?? '';
  return Object.keys(sidebarSections).includes(seg) ? seg : Object.keys(sidebarSections)[0];
}
