// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar, which IS safe
// (and expected) to be hand-edited between generator runs - the merge
// logic in scripts/wiki-extractors/merge.mjs never overwrites or removes
// entries whose extracted source content has not changed.

import type { MarkdownPageDoc } from '../types';
import data from './pages.generated.json';

export const markdownPages = data as unknown as MarkdownPageDoc[];

export function getPage(slug: string) {
  return markdownPages.find((p) => p.slug === slug);
}
